server:
  port: 8888

spring:
  application:
    name: configserver
  cloud:
    config:
      server:
        health:
          enabled: false
        git:
          uri: https://github.com/thakkarnirav123/cloud-core.git
      discovery:
        enabled: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF